/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Nat,
  'selectedWeight' : IDL.Text,
  'address' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'productName' : IDL.Text,
  'selectedWeight' : IDL.Text,
  'address' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'submitOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Nat,
    'selectedWeight' : IDL.Text,
    'address' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'productName' : IDL.Text,
    'selectedWeight' : IDL.Text,
    'address' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'submitOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };